# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ponderacao_temporal_cpp <- function(serie_temporal, kt) {
    .Call(`_smapOnsR_ponderacao_temporal_cpp`, serie_temporal, kt)
}

rodada_varios_dias_cpp <- function(modelo, inicializacao, area, precipitacao, evapotranspiracao, Emarg, numero_dias) {
    .Call(`_smapOnsR_rodada_varios_dias_cpp`, modelo, inicializacao, area, precipitacao, evapotranspiracao, Emarg, numero_dias)
}

